runtime: php81 # version of php
env: standard # set app engine env to standard

runtime_config:
  document_root: public

env_variables:
  APP_KEY: base64:fWySwhFLVyKZ1wiOC5gN29v7vC1g8GE5LbnF2mDWPPI=
  APP_LOG: errorlog
  STORAGE_DIR: /tmp
